import { useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { landingShowcase } from "../data/landingContent";

function ShowcaseVisual({ id }) {
  if (id === "strategy") return <div className="showcase-ui showcase-ui--strategy"><aside><span>SECTIONS</span><b>Technical questions</b><b>Behavioral questions</b><b>Road map</b></aside><main><header><strong>Technical Questions</strong><em>Role-specific</em></header><article><i>Q1</i><div><b>Explain an approach you would use for a scalable feature.</b><p>Intent · Test practical reasoning and trade-off awareness.</p></div></article><article><i>Q2</i><div><b>Show how you would communicate a project decision.</b><p>Model answer guidance available in the report.</p></div></article></main><section><span>MATCH CONTEXT</span><div className="showcase-ui__score">Fit</div><p>Skill gaps are prioritized beside your plan.</p></section></div>;
  if (id === "intelligence") return <div className="showcase-ui showcase-ui--intelligence"><header><span>ATS INTELLIGENCE</span><b>Make every application more explainable.</b><p>Alignment insight based on your saved profile and target role.</p></header><div className="showcase-ui__metrics"><article><span>Keyword alignment</span><b>Coverage</b><i /></article><article><span>Skill evidence</span><b>Evidence</b><i /></article><article><span>Resume completeness</span><b>Detected</b><i /></article></div><footer><b>What the role asks for</b><span>Prioritized requirements appear with evidence status.</span></footer></div>;
  return <div className="showcase-ui showcase-ui--roadmap"><header><span>ACTIVE IMPROVEMENT PLAN</span><b>Learning Roadmap</b><p>Weekly focus · realistic effort · progress</p></header><div className="showcase-ui__roadmap-list"><article><i>01</i><div><b>Strengthen technical foundations</b><span>Focused tasks and curated resources</span></div><em>In progress</em></article><article><i>02</i><div><b>Build role-relevant proof</b><span>Practice scenarios and project evidence</span></div><em>Next</em></article><article><i>03</i><div><b>Rehearse interview answers</b><span>Use your saved interview questions</span></div><em>Planned</em></article></div></div>;
}

export default function ProductShowcase() {
  const [activeId, setActiveId] = useState(landingShowcase[0].id);
  const active = landingShowcase.find((item) => item.id === activeId) || landingShowcase[0];
  return <section className="landing-showcase landing-section" data-section="showcase"><div className="landing-showcase__intro"><span className="landing-eyebrow">PRODUCT IN ACTION</span><h2>One role. A more complete view of your <em>next move.</em></h2><p>Move from role analysis to focused preparation without losing the context behind each recommendation.</p><div className="landing-showcase__tabs" role="tablist" aria-label="Product views">{landingShowcase.map((item) => <button key={item.id} role="tab" type="button" aria-selected={active.id === item.id} className={active.id === item.id ? "is-active" : ""} onClick={() => setActiveId(item.id)}>{item.label}</button>)}</div></div><motion.div className="landing-showcase__frame" layout><AnimatePresence mode="wait"><motion.div key={active.id} initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }} transition={{ duration: .28 }}><div className="landing-showcase__frame-head"><span>{active.eyebrow}</span><i /><i /><i /></div><ShowcaseVisual id={active.id} /></motion.div></AnimatePresence></motion.div><div className="landing-showcase__caption"><span>{active.eyebrow}</span><h3>{active.title}</h3><p>{active.body}</p></div></section>;
}
